server:
  port: 1001
  context-path: /
 
# 数据源配置
spring:
  datasource:
    # Druid 其他配置如 sql 监控这里省略了
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.197.130:3307/testspring
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
eureka:
  instance:
    hostname: localhost  #eureka客户端主机实例名称
    appname: microservice-student  #客户端服务名
    instance-id: microservice-student:1001XX22 #客户端实例名称
    prefer-ip-address: true #显示IP
  client: 
    service-url: 
      # 单机 
      defaultZone: http://localhost:2001/eureka   
      #把服务注册到eureka注册中心
      #defaultZone: http://eureka2001.cun.com:2001/eureka/,http://eureka2002.cun.com:2002/eureka/,http://eureka2003.cun.com:2003/eureka/ # 集群
      
info: 
   developer: linhongcun
   tel: 15768128080
    